name: Setup Node.js

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
    - name: Get pnpm store path
      shell: sh
      id: pnpm-cache
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
