packages:
  - packages/**
  - '!**/*bun*/**'

onlyBuiltDependencies:
  - esbuild
  - msw

overrides:
  typescript: ^6.0.3

packageExtensions:
  hono-react-router-adapter:
    peerDependencies:
      vite: "*"
