#! /usr/bin/env node

import path from 'node:path'
import * as process from 'node:process'
import { parseArgs } from 'node:util'

import { publish } from './publish.ts'
import { DEFAULT_TAR_NAME, RELEASE_NOTES } from './utils.ts'

const HELP = `\
Usage: ${path.parse(String(process.argv[1])).name} [options]

Publish the package to GitHub Releases

Options:
  --filename <string>  Package filename (default: "${DEFAULT_TAR_NAME}")
  --public             Creating a public release (default: false)
  --notes <string>     Release notes. Passing \`${RELEASE_NOTES.CHANGESETS}\` will automatically generate release notes using the changelog generated by the changesets. (default: "")
  -h, --help           Display help for command
`

const run = async () => {
  const { values: opts } = parseArgs({
    options: {
      filename: { type: 'string', default: DEFAULT_TAR_NAME },
      public: { type: 'boolean', default: false },
      notes: { type: 'string', default: RELEASE_NOTES.NONE },
      help: { type: 'boolean', short: 'h', default: false },
    },
  })

  if (opts.help) {
    process.stdout.write(HELP)
    process.exit(0)
  }

  await publish(opts.filename, opts.notes, !opts.public)
}

run()
