#! /usr/bin/env node

import { Command } from 'commander'

import { publish } from './publish.ts'
import { DEFAULT_TAR_NAME, RELEASE_NOTES } from './utils.ts'

const run = async () => {
  const opts = new Command()
    .description('Publish the package to GitHub Releases')
    .option('--filename <string>', `Package filename`, DEFAULT_TAR_NAME)
    .option('--public', `Creating a public release`, false)
    .option(
      '--notes <string>',
      `Release notes. Passing \`${RELEASE_NOTES.CHANGESETS}\` will automatically generate release notes using the changelog generated by the changesets.`,
      RELEASE_NOTES.NONE,
    )
    .parse()
    .opts<{ filename: string; public: boolean; notes: string }>()

  await publish(opts.filename, opts.notes, !opts.public)
}

run()
