export const colors = {
  bg: {
    DEFAULT: { value: { _dark: 'white', base: 'black' } },
    emphasized: { value: { _dark: '{colors.gray.800}', base: '{colors.gray.200}' } },
    error: { value: { _dark: '{colors.red.950}', base: '{colors.red.50}' } },
    info: { value: { _dark: '{colors.blue.950}', base: '{colors.blue.50}' } },
    inverted: { value: { _dark: 'white', base: 'black' } },
    muted: { value: { _dark: '{colors.gray.900}', base: '{colors.gray.100}' } },
    panel: { value: { _dark: '{colors.gray.950}', base: 'white' } },
    subtle: { value: { _dark: '{colors.gray.950}', base: '{colors.gray.50}' } },
    success: { value: { _dark: '{colors.green.950}', base: '{colors.green.50}' } },
    warning: { value: { _dark: '{colors.orange.950}', base: '{colors.orange.50}' } },
  },
  border: {
    DEFAULT: { value: { _dark: '{colors.gray.800}', base: '{colors.gray.300}' } },
    emphasized: { value: { _dark: '{colors.gray.700}', base: '{colors.gray.300}' } },
    error: { value: { _dark: '{colors.red.400}', base: '{colors.red.500}' } },
    info: { value: { _dark: '{colors.blue.400}', base: '{colors.blue.500}' } },
    inverted: { value: { _dark: '{colors.gray.200}', base: '{colors.gray.800}' } },
    muted: { value: { _dark: '{colors.gray.900}', base: '{colors.gray.100}' } },
    subtle: { value: { _dark: '{colors.gray.950}', base: '{colors.gray.50}' } },
    success: { value: { _dark: '{colors.green.400}', base: '{colors.green.500}' } },
    warning: { value: { _dark: '{colors.orange.400}', base: '{colors.orange.500}' } },
  },
  fg: {
    DEFAULT: { value: { _dark: '{colors.gray.50}', base: 'black' } },
    error: { value: { _dark: '{colors.red.400}', base: '{colors.red.500}' } },
    info: { value: { _dark: '{colors.blue.300}', base: '{colors.blue.600}' } },
    inverted: { value: { _dark: 'black', base: '{colors.gray.50}' } },
    muted: { value: { _dark: '{colors.gray.400}', base: '{colors.gray.600}' } },
    subtle: { value: { _dark: '{colors.gray.500}', base: '{colors.gray.400}' } },
    success: { value: { _dark: '{colors.green.300}', base: '{colors.green.600}' } },
    warning: { value: { _dark: '{colors.orange.300}', base: '{colors.orange.600}' } },
  },
  gray: {
    border: { value: { _dark: '{colors.gray.800}', base: '{colors.gray.200}' } },
    contrast: { value: { _dark: 'black', base: 'white' } },
    emphasized: { value: { _dark: '{colors.gray.700}', base: '{colors.gray.300}' } },
    fg: { value: { _dark: '{colors.gray.200}', base: '{colors.gray.800}' } },
    focusRing: { value: { _dark: '{colors.gray.400}', base: '{colors.gray.400}' } },
    muted: { value: { _dark: '{colors.gray.800}', base: '{colors.gray.200}' } },
    solid: { value: { _dark: 'white', base: '{colors.gray.900}' } },
    subtle: { value: { _dark: '{colors.gray.900}', base: '{colors.gray.100}' } },
  },
} as const
