export const conditions = {
  baseuiNestedDialogBackdrop: '[data-base-ui-inert]:has(~ &[data-nested])',
  ending: '&[data-ending-style]',
  fits: '&:not([data-has-overflow-x], [data-has-overflow-y])',
  hasContent: '&:not(:empty)',
  hover: '&:is(:hover, [data-hover], [data-hovering])',
  limited: '&[data-limited]',
  peerEnding: '[data-ending-style] ~ &',
  placeholderShown: '&:is(:placeholder-shown, [data-placeholder-shown], [data-placeholder])',
  placementBottom: '&[data-side=bottom]',
  placementCenter: '&[data-side=none]',
  placementInlineEnd: '&:is([data-side=right], [data-side=inline-end])',
  placementInlineStart: '&:is([data-side=left], [data-side=inline-start])',
  placementTop: '&[data-side=top]',
  scrolling: '&:is([data-scrolling])',
  starting: '&[data-starting-style]',
  swipeLeft: '&[data-swipe-direction=left]',
  swipeRight: '&[data-swipe-direction=right]',
} as const
