name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
      - uses: ./.github/actions/setup-node
      - run: pnpm i
      - name: Create Release Pull Request or Trigger publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          commit: "chore: Bump version for release"
          title: "chore: Bump version for release"
          publish: pnpm changeset tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo '${{steps.changesets.outputs.publishedPackages}}' | jq -c '.[]' | while read -r package; do
            pnpm --filter=$(echo $package | jq -r '.name') gh-publish --notes="changesets:autodetect"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
