name: Test

on: [pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: prepare
        run: |
          pnpm i
          pnpm --filter=@yamatomo/playwright exec playwright install --with-deps
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
