name: Test

on: [pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node
      - name: prepare
        run: |
          pnpm i
          pnpm --filter=@yamatomo/playwright exec playwright install --with-deps
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
