name: Test

on: [pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
      - uses: ./.github/actions/setup-node
      - name: prepare
        run: |
          pnpm i
          pnpm --filter=@yamatomo/playwright exec playwright install --with-deps
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
